### ISSUE TITLE
Release 0.0.6 not available on rubygems

### ISSUE THREAD

**Issue by mikepenz** [kazyApp/danger-findbugs#11]
Thank you very much for this great plugin. 

I am currently trying to have findbugs results directly used from the already run static code analysis on my CI. So it seems you actually added a feature to skip gradle execution in v0.0.6 

Sadly it seems this release is not yet available here: https://rubygems.org/gems/danger-findbugs 
As far as I can see Danger fetches the gem from there. 

It would be really awesome if you could update the plugin so the new `skip_gradle_task` can be used :)

Thanks a lot!

**Comment by mathroule** [comment]
The plugin has an issue it will be fixed by https://github.com/kazy1991/danger-findbugs/pull/12.

**Comment by kazyApp** [comment]
Please try v0.0.8
